### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by DecimalTurn** [cristianbuse/VBA-FastDictionary#6]
Many issues on https://github.com/VBA-tools/VBA-Dictionary are related to the fact that people downloaded the raw .cls file from the GitHub UI and ended up with a file with LF line endings. 

Perhaps it would be good to start on a good note with this new project and keep CRLF on GitHub instead of normalizing to LF. I haven't seen any case where normalizing to LF for VBA files was actually useful.

**Comment by cristianbuse** [comment]
Hi Martin,

Thanks for the suggestion!

The raw file basically imports as a module instead of a class. I assume this is the side effect of normalizing to LF.

I actually tried fixing this on other repositories and just gave up as I could not find a way to do it. I played with git settings as others suggested but never found the actual solution. I made sure that the zip and the latest release is fine though.

If you know what I need to do, then please let me know. Or make a pull request. Many thanks!
