### ISSUE TITLE
Possibly bug in enumerator function NewEnum() 

### ISSUE THREAD

**Issue by MarioAnthes** [cristianbuse/VBA-FastDictionary#8]
Hi Cristian,

Using your excellent Dictionary class I was hit by a bug which caused crashing the host application (Excel in this case).
To reproduce the bug I wrote a small test:

```
Sub Main()
    Dim dic As Dictionary
    Set dic = New Dictionary
    dic.Add "key1", 1
    dic.Add "key2", 2
    Dim v As Variant
    For Each v In dic
        Debug.Print v, dic.Item(v)
    Next
    Debug.Print "Everything fine so far..."

    ShowDic dic
End Sub

Private Sub ShowDic(ByRef dic As Dictionary)
    Dim v As Variant
    ' this causes error and/or crash:
    For Each v In dic
        Debug.Print v, dic.Item(v)
    Next
End Sub
```

Errors/crashes don't occur with `ByVal dic As Dictionary` or `ByVal dic As Object`, but with `ByRef dic As Dictionary`, `ByRef dic As Object`, `ByVal dic As Variant` and `ByRef dic As Variant`, which are all working fine with dic declared as Scripting.Dictionary

**Comment by cristianbuse** [comment]
Hi @MarioAnthes 

This is a VBA x64 bug. I wrote about it a few years ago [here](https://stackoverflow.com/q/63848617/8488913). It is a compiler bug where the stack pointer is not updated properly. It has nothing to do with the Dictionary class - any custom class returning an enumerator has the exact same issue. A Scripting.Dictionary or a Collection does not have that problem as the stack is handled differently for classes in dll.

I did mention this in the Readme of this repo as a warning but there is nothing I can do about it. As per the answer to the question I linked above, the best workaround I ever found was to use a second class to handle all enumerators but I did not add it to this repo because the intention was to have a single replacement class for scripting dict.

Thanks for the feedback!

**Comment by MarioAnthes** [comment]
Apologies, I should have known as I've read your post on stackoverflow and used your EnumHelper class already several times due to this nasty VBA x64 bug. Many thanks for the reply. 👍

**Comment by cristianbuse** [comment]
@MarioAnthes This is not an issue in the latest version. I have added [code to add extra stack space](https://github.com/cristianbuse/VBA-FastDictionary/blob/d45640814b0caec5cafef1643630be4db76b674f/src/Dictionary.cls#L1262-L1275). No need for other workarounds anymore :)

**Comment by cristianbuse** [comment]
Please note that release [v.2.2.0](https://github.com/cristianbuse/VBA-FastDictionary/releases/tag/v2.2.0) also adds extra stack space to avoid similar stack overlap issues with ```Class_Terminate``` e.g. [VBA takes wrong branch at If-statement - severe compiler bug?](https://stackoverflow.com/questions/65041832/vba-takes-wrong-branch-at-if-statement-severe-compiler-bug)
